#!/usr/bin/env python

from util import *
from lisp.interpreter import Interpreter
from os.path import dirname, join

import argparse
parser = argparse.ArgumentParser()
parser.add_argument('-d', help='get debug output', action='store_true', default=False)
parser.add_argument('-m', help='get macroexpansion output', action='store_true', default=False)
parser.add_argument('-c', help='clear environment. Don\'t read in stdlib first', action='store_true', default=False)
parser.add_argument('-e', help='get verbose error reporting', action='store_true', default=False)

args = parser.parse_args()

interpr = Interpreter(args.d, args.m)
if not args.c:
    interpret_file(join(dirname(__file__), "stdlib.lisp"), interpr)
repl(interpr, args.e)
